GET http://localhost:3000/

###

GET http://localhost:3000/allocation/for-user?userId=f32fbcfe-2351-4264-bafe-040274f469db&pageNum=1

###


GET http://localhost:3000/posts?page=10
###

GET http://localhost:3000/post/23378d4f-8535-42a3-8276-632e86286110

###

GET http://localhost:3000/annotation/by-user/?userId=f32fbcfe-2351-4264-bafe-040274f469db&postId=013ce342-605f-4df3-b5e2-96e5dd3ecb6c

###

POST http://localhost:3000/annotations
content-type : application/json

{
    "userId" : "f32fbcfe-2351-4264-bafe-040274f469db",
    "postId" : "0172a3d5-3347-4bfc-addd-ce81cf402288",
    "annotations" : [
         { "key": "ogbv", "value": "1" },
         { "key": "hate", "value": "0" }
    ]
}

###

POST http://localhost:3000/login
content-type : application/json

{
    "username":"annotator_a",
    "password" : "pw_ann_a"
} 

###

GET http://localhost:3000/dashboard

###

GET http://localhost:3000/annotations/type/csv