# Contains definitions for all kubernetes resources needed by ogbv-ml-rest
# If the file gets too large or unwieldy, feel free to separete

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogbv-ml-rest-cache
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogbv-ml-rest-assets
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accesModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ogbv-ml-rest
  labels:
    app.kubernetes.io/name: ogbv-ml-rest

spec:
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: ogbv-ml-rest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ogbv-ml-rest

    spec:
      volumes:
        - name: ogbv-ml-rest-cache
          persistentVolumeClaim:
            claimName: ogbv-ml-rest-cache
        - name: ogbv-ml-rest-asets
          persistentVolumeClaim:
            claimName: ogbv-ml-rest-assets
      containers:
        - name: ogbv-ml-rest
          image: tattletech/ogbv-ml-rest:7bc5787
          resources:
            limits:
              cpu: 256Mi
              memory: 4Gi
            requests:
              cpu: 256Mi
              memory: 4Gi
          imagePullPolicy: Always
          command: ["uvicorn"]
          args:
            ["sentiment_analyzer.api:app", "--host", "0.0.0.0", "--port", "80"]
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/root/.cache/huggingface/transformers"
              name: ogbv-ml-rest-cache
            - mountPath: "/app/assets"
              name: ogbv-ml-rest-assets
---
apiVersion: v1
kind: Service
metadata:
  name: ogbv-ml-rest
  labels:
    app.kubernetes.io/name: ogbv-ml-rest
spec:
  selector:
    app.kubernetes.io/name: ogbv-ml-rest
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
