# A docker compose that spins up the DB, DB-GUI and the Phoenix App. 
# Can be used to test how the app would work in the production. 
# The App uses an .env.local environment file. It can be copied from the .env.local.example file.
name: uli-community-prod

services:
  db:
    image: pgvector/pgvector:pg14
    restart: always
    environment:
      - POSTGRES_USER=uli_community
      - POSTGRES_PASSWORD=weak_password
      - POSTGRES_DB=uli_community_prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ~/data/uli_community_prod/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db_gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  migrate:
    image: uli-community:local
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    command: [ "/app/bin/uli_community", "eval", "UliCommunity.Release.migrate()" ]

  app:
    image: uli-community:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.local
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 4000:4000
