name: "Build For PR Review - Both Browsers"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  chrome-publish:
    name: "Build For PR Review"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Development Branch"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit SHA
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Build and Test"
        run: |
          cd browser-extension/plugin
          ls
          pwd
          npm install
          npm run build
          mv dist/ extension-chrome/
          npm run build:firefox
          mv dist/ extension-firefox/

      - name: "Upload dist folder as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: extension-artifacts
          path: |
            browser-extension/plugin/extension-firefox/
            browser-extension/plugin/extension-chrome/

      # - name: Debug GitHub Token Permissions
      #   run: echo ${{ secrets.GITHUB_TOKEN }}

      # - name: Create PR Comment with Artifact Link
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const artifact_url = `https://github.com/${{github.repository_owner}}/${{github.event.repository.name}}/actions/runs/${{ github.run_id }}`;
      #       const comment_body = `🛠 Your build files are available [here](${artifact_url}).`;
      #       await github.rest.issues.createComment({
      #         issue_number: context.payload.pull_request.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: comment_body
      #       });