name: "Create Plugin Release"

on:
  push:
    tags:
      - "v*"

jobs:
  pre-release:
    name: "Pre Release Extension"
    runs-on: "ubuntu-latest"
    environment:
      name: development
      url: "https://github.com/tattle-made/Uli/releases"

    steps:
      - name: "Checkout Development Branch"
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get commit SHA
        shell: bash
        run: |
          echo "setting variables"
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Build and Test"
        run: |
          cd browser-extension/plugin
          ls
          pwd
          npm install
          npm run build
          zip extension-chrome.zip ./dist/ -r
          rm -rf dist/
          npm run build:firefox
          zip extension-firefox.zip ./dist/ -r

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Development Build : ${{ github.event.inputs.version }}"
          files: |
            browser-extension/plugin/extension-chrome.zip
            browser-extension/plugin/extension-firefox.zip
