name: "PR Extensino for Firefox"

on:
  pull_request:
    branches:
      - actions

jobs:
  firefox-publish:
    name: "Pre Release Extension"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Development Branch"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get commit SHA
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Build and Test"
        run: |
          cd browser-extension/plugin
          ls
          pwd
          npm install
          npm run build:firefox
      
      - name: "Upload extension.zip as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: extension-firefox
          path: browser-extension/plugin/dist/

      - name: Create PR Comment with Artifact Link
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifact_url = `https://github.com/${{github.repository_owner}}/${{github.event.repository.name}}/actions/runs/${{ github.run_id }}`;
            const comment_body = `🛠 Your build files for FIREFOX are available [here](${artifact_url}).`;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_body
            });